# action.yml
name: 'SC-Go-Cross-Build'
author: StevenCyb
description: 'A golang cross build and public action.'
branding:
  icon: 'arrow-up-circle'  
  color: 'green'
inputs:
  github-token:
    description: 'Set this to env value "secrets.GITHUB_TOKEN"'
    required: true
  platform:
    description: 'Set this to one of {linux_386, linux_amd64, linux_arm, linux_arm64, darwin_amd64, windows_386, windows_amd64}'
    required: true
  include-files:
    description: 'Set files to include separated by space e.q. "README.md LICENSE"'
    required: false
    default: ''
runs:
  using: 'docker'
  image: './Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.platform }}
    - ${{ inputs.include-files }}
